# Global Risk Management Configuration
# These parameters will be used by the BasicRiskManager instance shared by all strategies.
risk_management:
  # Maximum position allowed for each symbol (in base currency).
  # If a symbol is not listed here, no position limit is enforced by this rule for it.
  max_position_per_symbol:
    BTC/USDT: 0.05  # Example: Max 0.05 BTC
    ETH/USDT: 0.5   # Example: Max 0.5 ETH
    # Add other symbols and their limits as needed
    # "ADA/USDT": 1000

  # Maximum percentage of available quote currency balance to be used for a single order.
  # e.g., 0.02 means 2% of available USDT (if quote is USDT) can be used for one order.
  max_capital_per_order_ratio: 0.02 # Default was 0.1, reducing for more conservative example

  # Minimum nominal value of an order in the quote currency (e.g., USDT).
  # Orders with a value below this will be rejected.
  min_order_value: 10.0 # Example: 10 USDT (Binance's typical minimum is around 10 USDT)

# Strategy Configurations
strategies:
  - name: "SMABtc1m_ConfigRisk"
    module: "strategies.simple_sma_strategy"
    class: "SimpleSMAStrategy"
    symbols: ["BTC/USDT"]
    timeframe: "1m"
    params:
      short_sma_period: 10
      long_sma_period: 20
      # Parameters for MyOrderEventStrategyInMain davranışını taklit etmek için (eğer bu stratejiyi kullanıyorsanız)
      # max_orders_to_place: 1
      # order_amount: 0.0001
      # price_offset_factor: 0.90
      # trade_interval_bars: 3

  - name: "SMAEth5m_ConfigRisk"
    module: "strategies.simple_sma_strategy"
    class: "SimpleSMAStrategy"
    symbols: ["ETH/USDT"]
    timeframe: "5m"
    params:
      short_sma_period: 5
      long_sma_period: 12

  # You can also configure the MyOrderEventStrategyInMain (if it's adapted to be loaded this way)
  # Make sure the module path is correct if it's defined in main.py, or move it to strategies/
  # - name: "MainEventStrategyConfig"
  #   module: "main" # Or "main_module_name_if_main_is_not_directly_importable_as_such"
  #   class: "MyOrderEventStrategyInMain"
  #   symbols: ["BTC/USDT"]
  #   timeframe: "1m"
  #   params:
  #     max_orders_to_place: 1
  #     order_amount: 0.0001
  #     price_offset_factor: 0.90
  #     trade_interval_bars: 2 # Example: trade every 2 bars
yaml
